<?php
// $Id: uc_paydollar.module,v 1.2 2011/01/25 08:20:25 hswong3i Exp $

/**
 * @file
 * Process payments using PayDollar PayGate.
 */

/**
 * Implementation of hook_menu().
 */
function uc_paydollar_menu() {
  $items = array();

  $items['uc_paydollar/success'] = array(
    'title' => 'Order complete',
    'page callback' => 'uc_paydollar_success',
    'access callback' => 'uc_paydollar_access',
    'type' => MENU_CALLBACK,
    'file' => 'uc_paydollar.pages.inc',
  );
  $items['uc_paydollar/fail'] = array(
    'title' => 'Order complete',
    'page callback' => 'uc_paydollar_fail',
    'access callback' => 'uc_paydollar_access',
    'type' => MENU_CALLBACK,
    'file' => 'uc_paydollar.pages.inc',
  );
  $items['uc_paydollar/cancel'] = array(
    'title' => 'Order complete',
    'page callback' => 'uc_paydollar_cancel',
    'access callback' => 'uc_paydollar_access',
    'type' => MENU_CALLBACK,
    'file' => 'uc_paydollar.pages.inc',
  );
  // The main handler for complete transaction.
  $items['uc_paydollar/datafeed'] = array(
    'title' => 'Order complete',
    'page callback' => 'uc_paydollar_datafeed',
    'access callback' => 'uc_paydollar_access',
    'type' => MENU_CALLBACK,
    'file' => 'uc_paydollar.pages.inc',
  );

  return $items;
}

/**
 * Make sure anyone can complete their PayDollar PayGate orders.
 * Full access
 */
function uc_paydollar_access() {
  return TRUE;
}

/**
 * Implementation of hook_init().
 */
function uc_paydollar_init() {
  global $conf;
  $conf['i18n_variables'][] = 'uc_paydollar_checkout_button';
}

/**
 * Implementation of hook_form_alter().
 */
function uc_paydollar_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'uc_cart_checkout_review_form' && ($order_id = intval($_SESSION['cart_order'])) > 0) {
    $order = uc_order_load($order_id);

    if ($order->payment_method == 'paydollar') {
      unset($form['submit']);
      $form['#prefix'] = '<table id="two-checkout-review-table"><tr><td>';
      $form['#suffix'] = '</td><td>'. drupal_get_form('uc_paydollar_form', $order) .'</td></tr></table>';
    }
  }
}

/**
 * Implementation of hook_payment_method().
 */
function uc_paydollar_payment_method() {
  $gateways[] = array(
    'id' => 'paydollar',
    'name' => t('PayDollar PayGate'),
    'title' => t('PayDollar PayGate - provides secure, multi-channel, multi-lingual and multi-currency payment services.'),
    'review' => t('Credit card/PayPal'),
    'desc' => t('Process credit card or PayPal payments using PayDollar PayGate.'),
    'callback' => 'uc_payment_method_paydollar',
    'weight' => 1,
    'checkout' => FALSE,
    'no_gateway' => TRUE,
  );

  return $gateways;
}

/**
 * Callback for payment gateway settings.
 */
function uc_payment_method_paydollar($op, &$arg1) {
  switch ($op) {
    case 'order-view':
      $payref = db_result(db_query("SELECT payref FROM {uc_paydollar_datafeed} WHERE ref = %d ORDER BY cdatetime ASC", $arg1->order_id));
      if (empty($payref)) {
        $payref = t('Unknown');
      }
      return t('PayDollar Payment Reference Number:<br />@payref', array('@payref' => $payref));

    case 'settings':
      $form['paydollar']['uc_paydollar_id'] = array(
        '#type' => 'textfield',
        '#title' => t('PayDollar ID'),
        '#description' => t('The merchant id used for the PayDollar service.'),
        '#default_value' => variable_get('uc_paydollar_id', '1'),
      );
      $form['paydollar']['uc_paydollar_handler'] = array(
        '#type' => 'select',
        '#title' => t('PayDollar server'),
        '#description' => t('Sign up for and use a Sandbox account for testing.'),
        '#options' => array(
          'https://test.paydollar.com/b2cDemo/eng/payment/payForm.jsp' => t('Sandbox'),
          'https://www.paydollar.com/b2c2/eng/payment/payForm.jsp' => t('Live'),
        ),
        '#default_value' => variable_get('uc_paydollar_handler', 'https://test.paydollar.com/b2cDemo/eng/payment/payForm.jsp'),
      );
      $form['paydollar']['uc_paydollar_currency'] = array(
        '#type' => 'select',
        '#title' => t('Currency code'),
        '#description' => t('Transactions can only be processed in one of the listed currencies.'),
        '#options' => array(
          '344' => 'HKD',
          '840' => 'USD',
          '702' => 'SGD',
          '156' => 'CNY',
          '392' => 'JPY',
          '901' => 'TWD',
          '036' => 'AUD',
          '978' => 'EUR',
          '826' => 'GBP',
          '124' => 'CAD',
        ),
        '#default_value' => variable_get('uc_paydollar_currency', '344'),
      );
      $form['paydollar']['uc_paydollar_language'] = array(
        '#type' => 'select',
        '#title' => t('Language'),
        '#description' => t('Please choose the language page.'),
        '#options' => array(
          'E' => t('English'),
          'C' => t('Traditional Chinese'),
          'X' => t('Simplified Chinese'),
          'K' => t('Korean'),
          'J' => t('Japanese'),
        ),
        '#default_value' => variable_get('uc_paydollar_language', 'E'),
      );
      $form['paydollar']['uc_paydollar_checkout_button'] = array(
        '#type' => 'textfield',
        '#title' => t('Order review submit button text'),
        '#description' => t('Provide PayDollar PayGate specific text for the submit button on the order review page.'),
        '#default_value' => variable_get('uc_2checkout_checkout_button', t('Submit Order')),
      );

      return $form;
  }
}

/**
 * Form to build the submission to PayDollar.com in HTML hidden form.
 */
function uc_paydollar_form($form_state, $order) {
  $data = array(
    'merchantId' => variable_get('uc_paydollar_id', '1'),
    'amount' => $order->order_total,
    'orderRef' => $order->order_id,
    'currCode' => variable_get('uc_paydollar_currency', '344'),
    'successUrl' => url('uc_paydollar/success/'. $order->order_id, array('absolute' => TRUE)),
    'failUrl' => url('uc_paydollar/fail/'. $order->order_id, array('absolute' => TRUE)),
    'cancelUrl' => url('uc_paydollar/cancel/'. $order->order_id, array('absolute' => TRUE)),
    'payType' => 'N',
    'actionUrl' => variable_get('uc_paydollar_handler', 'https://test.paydollar.com/b2cDemo/eng/payment/payForm.jsp'),
    'code' => 'paydollar',
    'orderId' => $order->order_id,
    'lang' => variable_get('uc_paydollar_language', 'E'),
    'remark' => uc_cart_get_id(),
  );

  $form['#action'] = variable_get('uc_paydollar_handler', 'https://test.paydollar.com/b2cDemo/eng/payment/payForm.jsp');

  foreach ($data as $name => $value) {
    if (!empty($value)) {
      $form[$name] = array('#type' => 'hidden', '#value' => $value);
    }
  }

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => variable_get('uc_paydollar_checkout_button', t('Submit Order')),
  );

  return $form;
}
